### ISSUE TITLE
xADGroup fail on get-dscconfiguration when there's only 1 user in group

### ISSUE THREAD

**Issue by AlexeyArzhenovskiy** [PowerShell/xActiveDirectory#161]
Configuration:

```
configuration ADGroup
{

 Import-DscResource -ModuleName xActiveDirectory

    Node localhost
    {
        xADGroup "DomainJoin Group"
        {
            GroupName = "DomainJoinRights"
            MembersToInclude = "DomainJoin"
        }
    }
}
```

Set-TargetResource work perfectly, but when you run get-dscconfiguration you'll get 

http://take.ms/BVtvI

```
VERBOSE: An LCM method call arrived from computer DC001A with user sid S-1-5-21-1793956226-513310661-1984400958-500.
VERBOSE: [DC001A]: LCM:  [ Start  Get      ]      
VERBOSE: [DC001A]:                            [[xADGroup]DomainJoin Group] Retrieving group membership based on 'SamAccountName' property.
Get-DscConfiguration : GetConfiguration did not succeed.
At line:1 char:1
+ Get-DscConfiguration -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (MSFT_DSCLocalConfigurationManager:root/Microsoft/...gurationManager) [Get-DscConfiguration], CimException
    + FullyQualifiedErrorId : MI RESULT 1,Get-DscConfiguration
```

Error in event log:

```
Job {3E5FC7B3-B556-11E7-8422-00155D01AF2C} : 
Message Unable to cast object of type 'System.String' to type 'System.Collections.IList'.
Parameter name: value 
HResult -2147024809 
StackTrack    at Microsoft.Management.Infrastructure.Internal.Data.CimPropertyOfInstance.set_Value(Object value)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.ResourceProviderAdapter.GetTargetResource(IntPtr resourceConfigurationInstanceHandle, IntPtr nonResourcePropetiesHandle, IntPtr metaConfigHandle, IntPtr regInstanceHandle, IStreamsHandler plugInStreamsHandler, IntPtr& outputInstanceHandle, IntPtr& errorInstanceHandle)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscPluginManagedEntryWrapper.Get(IntPtr provContext, IntPtr instance, IntPtr nonResourcePropeties, IntPtr metaConfig, IntPtr regInstance, IntPtr outputInstance, IntPtr extendedError)
```

DSC can handle this if 'Members = $adGroupMembers' return value is array, not string.
aka if you add 2 users to group - everything works fine. (Or you already have users in group)

If you specify type for $adGroupMembers inside MSFT_xADGroup resource - it works fine too

```
[System.Array]$adGroupMembers = (Get-ADGroupMember @adGroupParams).$MembershipAttribute;
```

**Comment by johlju** [comment]
This seemed to have been resolved in PR #173.
