### ISSUE TITLE
xADObjectPermissionEntry: Error creating AD: PS Drive

### ISSUE THREAD

**Issue by jrdbarnes** [PowerShell/xActiveDirectory#446]
#### Details of the scenario you tried and the problem that is occurring
Trying to configure AD Object permission entry. Puppet calls invoke-dscresource, so this is the configuration I've attached below.

Sometimes the Invoke-DSCResource completes successfully, but I haven't been able to identify what the difference is. These configurations were working successfully with 2.26.0.0. 

#### Verbose logs showing the problem

VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = Resourcetest,'className' =
MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer domaincontroller with user sid
[redactedSID].
VERBOSE: [domaincontroller]: LCM:  [ Start  Test     ]  [[xADObjectPermissionEntry]DirectResourceAccess]
VERBOSE: [domaincontroller]: LCM:  [ End    Test     ]  [[xADObjectPermissionEntry]DirectResourceAccess] False in 0.0160
seconds.
PowerShell DSC resource MSFT_xADObjectPermissionEntry  failed to execute Test-TargetResource functionality with error
message: System.InvalidOperationException: Error creating AD: PS Drive. (ADCOMMON0033) --->
System.Management.Automation.ProviderNotFoundException: Cannot find a provider with the name 'ActiveDirectory'.
   at System.Management.Automation.SessionStateInternal.GetProvider(PSSnapinQualifiedName providerName)
   at System.Management.Automation.SessionStateInternal.GetSingleProvider(String name)
   at Microsoft.PowerShell.Commands.NewPSDriveCommand.ProcessRecord()
   --- End of inner exception stack trace ---
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost

VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 0.384 seconds

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
$invokeParams = @{
    Name       = 'xADObjectPermissionEntry'
    ModuleName = @{
        modulename    = 'xActiveDirectory'
        moduleversion = '3.0.0.0'
    }
    Method     = 'test'
    Property   = @{
        'ensure' = 'present';
        'path' = 'CN=computer,OU=Managed,DC=domain,DC=local';
        'identityreference' = 'domain\groupname';
        'activedirectoryrights' = @('GenericAll');
        'accesscontroltype' = 'Allow';
        'objecttype' = '00000000-0000-0000-0000-000000000000';
        'activedirectorysecurityinheritance' = 'None';
        'inheritedobjecttype' = '00000000-0000-0000-0000-000000000000'
    }
}

Invoke-DscResource @invokeParams
```

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2019 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1809
WindowsBuildLabEx    : 17763.1.amd64fre.rs5_release.180914-1434
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running
PSVersion                      5.1.17763.592
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.592
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
3.0.0.0

**Comment by jrdbarnes** [comment]
This seems to have been caused by using invoke-dscresource with multiple versions of the xActiveDirectory module. Closing as not an issue
